const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';
const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_ERROR = 'LOGOUT_ERROR';

const MESSAGE_SENDING = 'MESSAGE_SENDING';
const MESSAGE_SENT = 'MESSAGE_SENT';
const MESSAGE_ERROR = 'MESSAGE_ERROR';

const FETCH_MESSAGES = 'FETCH_MESSAGES';
const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_ERROR= 'FETCH_ERROR';

export const types = {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_ERROR,
    LOGOUT_REQUEST,
    LOGOUT_SUCCESS,
    LOGOUT_ERROR,
    MESSAGE_SENDING,
    MESSAGE_SENT,
    MESSAGE_ERROR,
    FETCH_MESSAGES,
    FETCH_SUCCESS,
    FETCH_ERROR

}

