version: '3.8'

services:
  # frontend_app:
  #   container_name: react_app
  #   build: 
  #     context: ./Chatter
  #     dockerfile: Dockerfile
  db:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend_app:
    container_name: django_app
    build: 
      context: ../backend
      dockerfile: Dockerfile
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --workers 2 --log-level debug --reload
    volumes:
      - ../backend:/usr/src/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
      
    depends_on:
      - db
  frontend_app:
    container_name: react_app
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ../frontend:/usr/src/app/frontend
    ports:
      - "80:3000"
    env_file:
      - ./.env
    depends_on:
      - backend_app
volumes:
  pgdata:
  redisdata: