version: '3.8'

services:
  # frontend_app:
  #   container_name: react_app
  #   build: 
  #     context: ./Chatter
  #     dockerfile: Dockerfile
  db:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend_app:
    container_name: django_app
    build: 
      context: ../backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/usr/src/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
      
    depends_on:
      - db
    
volumes:
  pgdata:
  redisdata: